"""Create the local SQLite catalog and insert intentionally small, reviewed seed data."""

from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
DATABASE = ROOT / "data" / "clearsip.db"
SCHEMA = ROOT / "data" / "schema.sql"
FDA_SWEETENER_SOURCE = "https://www.fda.gov/food/food-additives-petitions/aspartame-and-other-sweeteners-food"
FDA_CAFFEINE_SOURCE = "https://www.fda.gov/consumers/consumer-updates/spilling-beans-how-much-caffeine-too-much"


def main() -> None:
    DATABASE.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(DATABASE) as conn:
        # This is a development bootstrap, deliberately rebuilding its disposable local database.
        for table in ("label_assessments", "label_ingredients", "ingredient_profiles", "label_versions", "source_records", "catalog_discoveries", "product_packages", "ingredients", "beverage_variants", "beverage_families", "manufacturers", "product_ingredients", "products"):
            conn.execute(f"DROP TABLE IF EXISTS {table}")
        conn.executescript(SCHEMA.read_text())
        conn.executemany("INSERT INTO manufacturers VALUES (?, ?, ?)", [
            ("coca-cola-company", "The Coca-Cola Company", "https://www.coca-colacompany.com/"),
            ("monster-energy", "Monster Energy", "https://www.monsterenergy.com/"),
        ])
        conn.executemany("INSERT INTO beverage_families VALUES (?, ?, ?)", [
            ("coca-cola", "coca-cola-company", "Coca-Cola"), ("monster-energy", "monster-energy", "Monster Energy"),
        ])
        conn.executemany("INSERT INTO beverage_variants VALUES (?, ?, ?, ?, ?)", [
            ("coca-cola-zero-sugar", "coca-cola", "Coca-Cola Zero Sugar", None, "carbonated soft drink"),
            ("monster-zero-sugar", "monster-energy", "Monster Energy Zero Sugar", None, "energy drink"),
        ])
        conn.executemany("INSERT INTO product_packages VALUES (?, ?, ?, ?, ?, ?, ?)", [
            ("coca-cola-zero-sugar-12oz-us", "coca-cola-zero-sugar", None, None, "United States", "12 fl oz can", "active"),
            ("monster-zero-sugar-16oz-us", "monster-zero-sugar", None, None, "United States", "16 fl oz can", "active"),
        ])
        conn.executemany("INSERT INTO catalog_discoveries VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [
            ("coca-cola-original", "The Coca-Cola Company", "Coca-Cola", "Coca-Cola Original", "carbonated soft drink", "United States", "7.5, 8, 12, 16, 16.9, 20 fl oz; 1.25, 2 L", "variant", None, "https://www.coca-cola.com/us/en/brands/coca-cola/products/original", "2026-09-24", "needs_package_verification"),
            ("coca-cola-zero", "The Coca-Cola Company", "Coca-Cola", "Coca-Cola Zero Sugar", "carbonated soft drink", "United States", "7.5, 8, 12, 16, 16.9, 20 fl oz; 1.25, 2 L", "variant", None, "https://www.coca-cola.com/us/en/brands/coca-cola/products/zero", "2026-09-24", "needs_package_verification"),
            ("coca-cola-cherry", "The Coca-Cola Company", "Coca-Cola", "Coca-Cola Cherry", "carbonated soft drink", "United States", "7.5, 12, 16.9 fl oz; 2 L", "variant", None, "https://www.coca-cola.com/us/en/brands/coca-cola/products/coca-cola-flavors", "2026-09-24", "discovery_candidate"),
            ("coca-cola-cherry-zero", "The Coca-Cola Company", "Coca-Cola", "Coca-Cola Cherry Zero Sugar", "carbonated soft drink", "United States", "7.5, 12, 16.9, 20 fl oz; 2 L", "variant", None, "https://www.coca-cola.com/us/en/brands/coca-cola/products/coca-cola-flavors", "2026-09-24", "discovery_candidate"),
            ("coca-cola-vanilla", "The Coca-Cola Company", "Coca-Cola", "Coca-Cola Vanilla", "carbonated soft drink", "United States", "12, 16.9, 20 fl oz", "variant", None, "https://www.coca-cola.com/us/en/brands/coca-cola/products/coca-cola-flavors", "2026-09-24", "discovery_candidate"),
            ("sprite-original", "The Coca-Cola Company", "Sprite", "Sprite", "carbonated soft drink", "United States", "7.5, 8, 12, 13.2, 16.9, 20 fl oz; 1, 1.25, 2, 3 L", "variant", None, "https://www.coca-cola.com/us/en/brands/sprite/products", "2026-09-24", "needs_package_verification"),
            ("sprite-zero", "The Coca-Cola Company", "Sprite", "Sprite Zero Sugar", "carbonated soft drink", "United States", None, "unknown", None, "https://www.coca-cola.com/us/en/brands/sprite/products", "2026-09-24", "discovery_candidate"),
            ("sprite-chill", "The Coca-Cola Company", "Sprite", "Sprite Chill", "carbonated soft drink", "United States", None, "unknown", None, "https://www.coca-cola.com/us/en/brands/sprite/products", "2026-09-24", "discovery_candidate"),
            ("sprite-tea-peach", "The Coca-Cola Company", "Sprite", "Sprite + Tea Peach", "carbonated soft drink", "United States", "12, 20 fl oz", "variant", "Kroger exclusive", "https://www.coca-cola.com/us/en/brands/sprite/products", "2026-09-24", "discovery_candidate"),
            ("powerade-grape", "The Coca-Cola Company", "Powerade", "Powerade Grape", "sports drink", "United States", "20, 28 fl oz", "variant", None, "https://powerade-us-en.beta.cep.coca-cola.com/products/powerade", "2026-09-24", "needs_package_verification"),
            ("powerade-lemon-lime", "The Coca-Cola Company", "Powerade", "Powerade Lemon Lime", "sports drink", "United States", "20, 28 fl oz", "variant", None, "https://powerade-us-en.beta.cep.coca-cola.com/products/powerade", "2026-09-24", "needs_package_verification"),
            ("powerade-orange", "The Coca-Cola Company", "Powerade", "Powerade Orange", "sports drink", "United States", "12, 20, 28 fl oz", "variant", None, "https://powerade-us-en.beta.cep.coca-cola.com/products/powerade", "2026-09-24", "needs_package_verification"),
            ("powerade-zero-mixed-berry", "The Coca-Cola Company", "Powerade Zero", "Powerade Zero Sugar Mixed Berry", "sports drink", "United States", "12, 20, 28 fl oz", "variant", None, "https://powerade-us-en.alpha.cep.coca-cola.com/products/powerade-zero", "2026-09-24", "needs_package_verification"),
            ("dasani", "The Coca-Cola Company", "Dasani", "Dasani Purified Water", "bottled water", "United States", "10, 12, 16.9, 20 fl oz; 1, 1.5 L", "variant", None, "https://www.coca-cola.com/us/en/brands/dasani", "2026-09-24", "needs_package_verification"),
            ("pepsi", "PepsiCo", "Pepsi", "Pepsi", "carbonated soft drink", "United States", "7.5, 12, 16, 16.9, 20, 24 fl oz; 1, 1.25, 2 L", "variant", None, "https://www.pepsi.com/products/pepsi", "2026-09-24", "needs_package_verification"),
            ("diet-pepsi", "PepsiCo", "Pepsi", "Diet Pepsi", "carbonated soft drink", "United States", "7.5, 12, 16, 16.9, 20, 24 fl oz; 1, 1.25, 2 L", "variant", None, "https://www.pepsi.com/products/diet-pepsi", "2026-09-24", "needs_package_verification"),
            ("pepsi-zero", "PepsiCo", "Pepsi", "Pepsi Zero Sugar", "carbonated soft drink", "United States", "7.5, 12, 13, 16, 16.9, 20, 24, 33.8, 42.3, 67 fl oz; fountain", "variant", None, "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000018800", "2026-09-24", "needs_package_verification"),
            ("mountain-dew-original", "PepsiCo", "Mountain Dew", "Mountain Dew", "carbonated soft drink", "United States", "7.5, 12, 13, 16, 16.9, 20, 24, 33.8, 42.3, 67 fl oz; fountain/freeze", "variant", None, "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000000850", "2026-09-24", "needs_package_verification"),
            ("gatorade-cool-blue", "PepsiCo", "Gatorade", "Gatorade Cool Blue", "sports drink", "United States", "12, 20, 24, 28 fl oz", "variant", None, "https://www.pepsicoproductfacts.com/Home/Product?gtin=00052000324815", "2026-09-24", "needs_package_verification"),
            ("gatorade-strawberry-lemonade", "PepsiCo", "Gatorade", "Gatorade Strawberry Lemonade", "sports drink", "United States", "20 fl oz", "variant", None, "https://www.pepsicoproductfacts.com/Home/product?gtin=00052000104257", "2026-09-24", "needs_package_verification"),
            ("gatorade-water", "PepsiCo", "Gatorade", "Gatorade Water", "bottled water", "United States", "20, 23.7, 33.8 fl oz", "variant", None, "https://www.pepsicoproductfacts.com/Home/Product?gtin=00052000054903", "2026-09-24", "needs_package_verification"),
            ("aquafina", "PepsiCo", "Aquafina", "Aquafina Purified Water", "bottled water", "United States", "12, 16, 16.9, 20, 33.8, 42.3, 50.7 fl oz", "family", "Exact bottle/package label required", "https://www.pepsicoproductfacts.com/Home/Product?gtin=00012000001086", "2026-09-24", "discovery_candidate"),
            ("monster-ultra-zero", "Monster Energy", "Monster Ultra", "Monster Ultra Zero", "energy drink", "United States", "12, 16, 19.2, 24 oz", "variant", None, "https://www.monsterenergy.com/en-us/energy-drinks/zero-sugar/zero-ultra/", "2026-09-24", "needs_package_verification"),
            ("red-bull-original", "Red Bull", "Red Bull", "Red Bull Original", "energy drink", "United States", "8.4, 12, 16, 20 fl oz", "variant", None, "https://www.redbull.com/energydrink/red-bull-energy-drink", "2026-09-24", "needs_package_verification"),
            ("dr-pepper-blackberry", "Keurig Dr Pepper", "Dr Pepper", "Dr Pepper Blackberry", "carbonated soft drink", "United States", None, "unknown", "Package facts must be verified", "https://www.keurigdrpepper.com/keurig-dr-pepper-unveils-bold-new-flavors-across-iconic-u-s-cold-beverages-portfolio-27/", "2026-09-24", "discovery_candidate"),
            ("seven-up", "Keurig Dr Pepper", "7UP", "7UP", "carbonated soft drink", "United States", None, "unknown", "Brand-directory discovery; package facts required", "https://www.keurigdrpepper.com/brands/", "2026-09-24", "discovery_candidate"),
            ("snapple", "Keurig Dr Pepper", "Snapple", "Snapple Tea and Juice Drinks", "tea and juice drink", "United States", None, "unknown", "Brand-directory discovery; flavor/package facts required", "https://www.keurigdrpepper.com/brands/", "2026-09-24", "discovery_candidate"),
            ("bai", "Keurig Dr Pepper", "Bai", "Bai Flavored Drinks", "flavored drink", "United States", None, "unknown", "Brand-directory discovery; flavor/package facts required", "https://www.keurigdrpepper.com/brands/", "2026-09-24", "discovery_candidate"),
            ("lacroix", "National Beverage Corp.", "LaCroix", "LaCroix Sparkling Water", "sparkling water", "United States", None, "unknown", "Current package-size index requires direct label/FDC verification", "https://www.lacroixwater.com/", "2026-09-24", "discovery_candidate"),
            # Coffee starter batch: each source is a first-party page with label information.
            # These stay in discovery until an exact US package/UPC is attached to a versioned label.
            ("stok-unsweet-black-cold-brew", "Danone North America", "STōK", "STōK UN-SWEET Black Cold Brew Coffee", "ready-to-drink cold brew coffee", "United States", "48 fl oz bottle; 12 fl oz serving", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.stokbrew.com/cold-brew/cold-brew-coffee/unsweetened-cold-brew-coffee-48oz/", "2026-09-26", "needs_package_verification"),
            ("stok-not-too-sweet-black-cold-brew", "Danone North America", "STōK", "STōK NOT TOO SWEET Black Cold Brew Coffee", "ready-to-drink cold brew coffee", "United States", "48 fl oz bottle; 12 fl oz serving", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.stokbrew.com/cold-brew/cold-brew-coffee/not-too-sweet-cold-brew-coffee-48oz/", "2026-09-26", "needs_package_verification"),
            ("stok-espresso-blend-black-cold-brew", "Danone North America", "STōK", "STōK Espresso Blend Black Cold Brew Coffee", "ready-to-drink cold brew coffee", "United States", "48 fl oz bottle; 12 fl oz serving", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.stokbrew.com/cold-brew/cold-brew-coffee/unsweetened-black-espresso-cold-brew-coffee-48oz/", "2026-09-26", "needs_package_verification"),
            ("stok-extra-bold-black-cold-brew", "Danone North America", "STōK", "STōK Extra Bold Black Cold Brew Coffee", "ready-to-drink cold brew coffee", "United States", "48 fl oz bottle; 12 fl oz serving", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.stokbrew.com/cold-brew/cold-brew-coffee/extra-bold-cold-brew-coffee-48oz", "2026-09-26", "needs_package_verification"),
            ("stok-bright-mellow-cold-brew", "Danone North America", "STōK", "STōK UN-SWEET Bright & Mellow Black Cold Brew Coffee", "ready-to-drink cold brew coffee", "United States", "48 fl oz bottle; 12 fl oz serving", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.stokbrew.com/cold-brew/cold-brew-coffee/bright-mellow-cold-brew-coffee-48oz/", "2026-09-26", "needs_package_verification"),
            ("stok-decaf-unsweet-cold-brew", "Danone North America", "STōK", "STōK DECAF UN-SWEET Black Cold Brew Coffee", "ready-to-drink cold brew coffee", "United States", "48 fl oz bottle; 12 fl oz serving", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.stokbrew.com/cold-brew/cold-brew-coffee/unsweetened-decaf-cold-brew-coffee-48oz/", "2026-09-26", "needs_package_verification"),
            ("stok-decaf-not-too-sweet-cold-brew", "Danone North America", "STōK", "STōK DECAF NOT TOO SWEET Black Cold Brew Coffee", "ready-to-drink cold brew coffee", "United States", "48 fl oz bottle; 12 fl oz serving", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.stokbrew.com/cold-brew/cold-brew-coffee/not-too-sweet-decaf-cold-brew-coffee-48oz", "2026-09-26", "needs_package_verification"),
            ("la-colombe-everyday-draft-latte", "La Colombe Coffee Roasters", "La Colombe Draft Latte", "La Colombe Everyday Draft Latte", "ready-to-drink canned latte", "United States", "9 fl oz can", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.lacolombe.com/products/draft-latte", "2026-09-26", "needs_package_verification"),
            ("la-colombe-vanilla-draft-latte", "La Colombe Coffee Roasters", "La Colombe Draft Latte", "La Colombe Vanilla Draft Latte", "ready-to-drink canned latte", "United States", "9 fl oz can", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.lacolombe.com/products/vanilla-draft-latte", "2026-09-26", "needs_package_verification"),
            ("la-colombe-triple-draft-latte", "La Colombe Coffee Roasters", "La Colombe Draft Latte", "La Colombe Triple Draft Latte", "ready-to-drink canned latte", "United States", "9 fl oz can", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.lacolombe.com/products/triple-draft-latte", "2026-09-26", "needs_package_verification"),
            ("la-colombe-mocha-draft-latte", "La Colombe Coffee Roasters", "La Colombe Draft Latte", "La Colombe Mocha Draft Latte", "ready-to-drink canned latte", "United States", "9 fl oz can", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.lacolombe.com/products/mocha-draft-latte", "2026-09-26", "needs_package_verification"),
            ("la-colombe-caramel-draft-latte", "La Colombe Coffee Roasters", "La Colombe Draft Latte", "La Colombe Caramel Draft Latte", "ready-to-drink canned latte", "United States", "9 fl oz can", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.lacolombe.com/products/caramel-draft-latte", "2026-09-26", "needs_package_verification"),
            ("la-colombe-oatmilk-vanilla-draft-latte", "La Colombe Coffee Roasters", "La Colombe Draft Latte", "La Colombe Oatmilk Vanilla Draft Latte", "ready-to-drink canned oatmilk latte", "United States", "9 fl oz can", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.lacolombe.com/products/oatmilk-draft-latte-vanilla", "2026-09-26", "needs_package_verification"),
            ("la-colombe-oatmilk-everyday-draft-latte", "La Colombe Coffee Roasters", "La Colombe Draft Latte", "La Colombe Oatmilk Everyday Draft Latte", "ready-to-drink canned oatmilk latte", "United States", "9 fl oz can", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.lacolombe.com/products/oatmilk-draft-latte", "2026-09-26", "needs_package_verification"),
            ("dunkin-cold-brew-concentrate", "The J.M. Smucker Co.", "Dunkin' At Home", "Dunkin' Cold Brew Concentrate", "coffee concentrate", "United States", "31 fl oz bottle; 6 fl oz concentrate makes 12 fl oz prepared", "variant", "Manufacturer label page; nutrition facts use the concentrate serving", "https://www.dunkinathome.com/products/concentrates/cold-concentrates-black", "2026-09-26", "needs_package_verification"),
            ("dunkin-caramel-cold-brew-concentrate", "The J.M. Smucker Co.", "Dunkin' At Home", "Dunkin' Caramel Cold Brew Concentrate", "coffee concentrate", "United States", "31 fl oz bottle; 6 fl oz concentrate makes 12 fl oz prepared", "variant", "Manufacturer label page; nutrition facts use the concentrate serving", "https://www.dunkinathome.com/products/concentrates/cold-concentrates-caramel", "2026-09-26", "needs_package_verification"),
            ("dunkin-pumpkin-spice-cold-brew-concentrate", "The J.M. Smucker Co.", "Dunkin' At Home", "Dunkin' Pumpkin Spice Cold Brew Concentrate", "coffee concentrate", "United States", "31 fl oz bottle; 6 fl oz concentrate makes 12 fl oz prepared", "variant", "Seasonal manufacturer label page; nutrition facts use the concentrate serving", "https://www.dunkinathome.com/products/concentrates/cold-concentrates-pumpkin", "2026-09-26", "needs_package_verification"),
            ("starbucks-signature-black-cold-brew-concentrate", "North American Coffee Partnership", "Starbucks At Home", "Starbucks Cold Brew Multi-Serve Concentrate Signature Black", "coffee concentrate", "United States", "6 fl oz concentrate makes 12 fl oz prepared; bottle net contents not recorded", "unknown", "Manufacturer label page; serving is concentrate/prepared basis, not an RTD package", "https://athome.starbucks.com/products/cold-brew-multi-serve-concentrate-signature-black", "2026-09-26", "needs_package_verification"),
            ("starbucks-caramel-dolce-cold-brew-concentrate", "North American Coffee Partnership", "Starbucks At Home", "Starbucks Flavored Cold Brew Multi-Serve Concentrate Caramel Dolce", "coffee concentrate", "United States", "6 fl oz concentrate makes 12 fl oz prepared; bottle net contents not recorded", "unknown", "Manufacturer label page; serving is concentrate/prepared basis, not an RTD package", "https://athome.starbucks.com/products/cold-brew-flavored-multi-serve-concentrate-caramel-dolce", "2026-09-26", "needs_package_verification"),
            ("starbucks-madagascar-vanilla-cold-brew-concentrate", "North American Coffee Partnership", "Starbucks At Home", "Starbucks Flavored Cold Brew Multi-Serve Concentrate Madagascar Vanilla", "coffee concentrate", "United States", "6 fl oz concentrate makes 12 fl oz prepared; bottle net contents not recorded", "unknown", "Official product page found; capture complete nutrition panel before label ingestion", "https://athome.starbucks.com/products/cold-brew-flavored-multi-serve-concentrate-madagascar-vanilla", "2026-09-26", "discovery_candidate"),
            ("starbucks-brown-sugar-cinnamon-cold-brew-concentrate", "North American Coffee Partnership", "Starbucks At Home", "Starbucks Flavored Cold Brew Multi-Serve Concentrate Brown Sugar Cinnamon", "coffee concentrate", "United States", "6 fl oz concentrate makes 12 fl oz prepared; bottle net contents not recorded", "unknown", "Manufacturer label page; serving is concentrate/prepared basis, not an RTD package", "https://athome.starbucks.com/products/starbucks-cold-brew-multi-serve-concentrate-Brown-Sugar-Cinnamon", "2026-09-26", "needs_package_verification"),
            # Diverse, non-coffee expansion: first-party US product/portfolio evidence only.
            ("ocean-spray-100-juice-cranberry", "Ocean Spray Cranberries, Inc.", "Ocean Spray 100% Juice Blend", "100% Juice Blend Cranberry", "100% juice blend", "United States", "64 oz bottle", "variant", "Manufacturer product page; exact UPC/package match pending", "https://www.oceanspray.com/products/100-juice-blend-cranberry-64-oz", "2026-09-26", "discovery_candidate"),
            ("ocean-spray-cranberry-lime", "Ocean Spray Cranberries, Inc.", "Ocean Spray Cranberry Juice Cocktail", "Cranberry Juice Cocktail With Lime", "juice drink", "United States", "64 oz bottle", "variant", "Manufacturer product page; exact UPC/package match pending", "https://www.oceanspray.com/products/cranberry-juice-cocktail-with-lime-64-oz", "2026-09-26", "discovery_candidate"),
            ("ocean-spray-diet-cranberry", "Ocean Spray Cranberries, Inc.", "Ocean Spray Diet", "Diet Cranberry", "reduced-calorie juice drink", "United States", "64 oz bottle; 8 fl oz listed serving", "variant", "Manufacturer product page; exact UPC/package match pending", "https://www.oceanspray.com/products/diet-cranberry-juice-drink-64-oz", "2026-09-26", "discovery_candidate"),
            ("ocean-spray-cranberry-calcium", "Ocean Spray Cranberries, Inc.", "Ocean Spray Cranberry Juice Cocktail", "Cranberry Juice Cocktail With Calcium", "juice drink", "United States", "64 oz bottle", "variant", "Manufacturer product page; do not interpret calcium marketing as a health assessment", "https://www3.oceanspray.com/products/cranberry-juice-cocktail-with-calcium-64-oz", "2026-09-26", "discovery_candidate"),
            ("ocean-spray-cran-cherry", "Ocean Spray Cranberries, Inc.", "Ocean Spray Cran x", "Cran x Cherry", "cranberry-cherry juice drink", "United States", "64 oz bottle", "variant", "Manufacturer product page; exact UPC/package match pending", "https://www.oceanspray.com/products/cran-cherry-cranberry-cherry-juice-drink-64-oz", "2026-09-26", "discovery_candidate"),
            ("ocean-spray-diet-cranberry-lime", "Ocean Spray Cranberries, Inc.", "Ocean Spray Diet", "Diet Cranberry With Lime", "reduced-calorie juice drink", "United States", "64 oz bottle; 8 fl oz listed serving", "variant", "Manufacturer product page; exact UPC/package match pending", "https://www.oceanspray.com/products/diet-cranberry-juice-drink-with-lime-64-oz", "2026-09-26", "discovery_candidate"),
            ("ocean-spray-zero-sugar-cranberry", "Ocean Spray Cranberries, Inc.", "Ocean Spray ZERO Sugar", "ZERO Sugar Cranberry", "zero-sugar juice drink", "United States", "64 oz bottle; 8 fl oz listed serving", "variant", "Manufacturer page reports 0 g sugar per listed serving; attach a package label before claim assessment", "https://www2.oceanspray.com/products/zero-sugar-cranberry-64-oz", "2026-09-26", "needs_package_verification"),
            ("ocean-spray-cran-lemonade", "Ocean Spray Cranberries, Inc.", "Ocean Spray Cran x", "Cran x Lemonade", "cranberry-lemonade juice drink", "United States", "64 oz bottle", "variant", "Manufacturer product page; exact UPC/package match pending", "https://www.oceanspray.com/products/cran-lemonade-cranberry-lemonade-juice-drink-64-oz", "2026-09-26", "discovery_candidate"),
            ("v8-original-vegetable-juice", "Campbell Soup Company", "V8 Vegetable Juice", "Original 100% Vegetable Juice", "vegetable juice", "United States", "11.5 fl oz can; consumer-page serving is 8 fl oz", "variant", "Official foodservice package page; keep consumer/package label versions separate", "https://www.campbellsfoodservice.com/product/original-100-vegetable-juice-12/", "2026-09-26", "needs_package_verification"),
            ("v8-energy-peach-mango", "Campbell Soup Company", "V8 Energy", "Peach Mango", "tea-caffeine fruit and vegetable energy drink", "United States", "8 fl oz can (237 mL)", "variant", "Manufacturer page states 80 mg caffeine; attach exact package before full classification", "https://www.campbells.com/v8/products/v8-energy/peach-mango/", "2026-09-26", "needs_package_verification"),
            ("v8-energy-orange-pineapple", "Campbell Soup Company", "V8 Energy", "Orange Pineapple", "tea-caffeine fruit and vegetable energy drink", "United States", "8 fl oz can (237 mL)", "variant", "Manufacturer page states 80 mg caffeine; attach exact package before full classification", "https://www.campbells.com/v8/products/v8-energy/orange-pineapple/", "2026-09-26", "needs_package_verification"),
            ("v8-energy-pomegranate-blueberry", "Campbell Soup Company", "V8 Energy", "Pomegranate Blueberry", "tea-caffeine fruit and vegetable energy drink", "United States", "1 can listed serving; net can size not stated", "unknown", "Manufacturer page states 80 mg caffeine; attach exact package before full classification", "https://www.campbells.com/v8/products/v8-energy/pomegranate-blueberry/", "2026-09-26", "needs_package_verification"),
            ("v8-energy-black-cherry", "Campbell Soup Company", "V8 Energy", "Black Cherry", "tea-caffeine fruit and vegetable energy drink", "United States", "8 fl oz can (237 mL)", "variant", "Manufacturer page states 80 mg caffeine; attach exact package before full classification", "https://www.campbells.com/v8/products/v8-energy/black-cherry/", "2026-09-26", "needs_package_verification"),
            ("v8-energy-zero-sugar-cherry-lime", "Campbell Soup Company", "V8 Energy Zero Sugar", "Cherry Lime", "zero-sugar tea-caffeine energy drink", "United States", "1 can listed serving; net can size not stated", "unknown", "Manufacturer page reports 0 g sugar and named ingredients; attach package before claim assessment", "https://www.campbells.com/v8/products/v8-energy-zero-sugar/cherry-lime/", "2026-09-26", "needs_package_verification"),
            ("v8-energy-zero-sugar-blueberry-raspberry", "Campbell Soup Company", "V8 Energy Zero Sugar", "Blueberry Raspberry", "zero-sugar tea-caffeine energy drink", "United States", None, "unknown", "Official lineup discovery; individual label/GTIN required", "https://www.campbells.com/v8/v8-energy-zero-sugar/", "2026-09-26", "discovery_candidate"),
            ("v8-energy-zero-sugar-strawberry-lemonade", "Campbell Soup Company", "V8 Energy Zero Sugar", "Strawberry Lemonade", "zero-sugar tea-caffeine energy drink", "United States", None, "unknown", "Official lineup discovery; individual label/GTIN required", "https://www.campbells.com/v8/v8-energy-zero-sugar/", "2026-09-26", "discovery_candidate"),
            ("hint-water-watermelon", "Hint, Inc.", "hint water", "Watermelon", "still flavored water", "United States", "16 oz bottle", "variant", "Official flavor catalog; exact variant label still required", "https://www.drinkhint.com/pages/flavor", "2026-09-26", "discovery_candidate"),
            ("hint-water-blackberry", "Hint, Inc.", "hint water", "Blackberry", "still flavored water", "United States", "16 oz bottle", "variant", "Official flavor catalog; exact variant label still required", "https://www.drinkhint.com/pages/flavor", "2026-09-26", "discovery_candidate"),
            ("hint-water-pineapple", "Hint, Inc.", "hint water", "Pineapple", "still flavored water", "United States", "16 oz bottle", "variant", "Official flavor catalog; exact variant label still required", "https://www.drinkhint.com/pages/flavor", "2026-09-26", "discovery_candidate"),
            ("hint-water-crisp-apple", "Hint, Inc.", "hint water", "Crisp Apple", "still flavored water", "United States", "16 oz bottle", "variant", "Official flavor catalog; exact variant label still required", "https://www.drinkhint.com/pages/flavor", "2026-09-26", "discovery_candidate"),
            ("hint-water-georgia-peach", "Hint, Inc.", "hint water", "Georgia Peach", "still flavored water", "United States", "16 oz bottle", "variant", "Official flavor catalog; exact variant label still required", "https://www.drinkhint.com/pages/flavor", "2026-09-26", "discovery_candidate"),
            ("hint-water-cherry", "Hint, Inc.", "hint water", "Cherry", "still flavored water", "United States", "16 oz bottle", "variant", "Official flavor catalog; exact variant label still required", "https://www.drinkhint.com/pages/flavor", "2026-09-26", "discovery_candidate"),
            ("waterloo-black-cherry", "National Beverage Corp.", "Waterloo", "Black Cherry", "sparkling water", "United States", None, "unknown", "Official catalog discovery; exact package and label required", "https://www.drinkwaterloo.com/collections/all", "2026-09-26", "discovery_candidate"),
            ("waterloo-lemon-lime", "National Beverage Corp.", "Waterloo", "Lemon Lime", "sparkling water", "United States", None, "unknown", "Official catalog discovery; exact package and label required", "https://www.drinkwaterloo.com/collections/all", "2026-09-26", "discovery_candidate"),
            ("waterloo-strawberry", "National Beverage Corp.", "Waterloo", "Strawberry", "sparkling water", "United States", None, "unknown", "Official catalog discovery; exact package and label required", "https://www.drinkwaterloo.com/collections/all", "2026-09-26", "discovery_candidate"),
            ("waterloo-tropical-fruit", "National Beverage Corp.", "Waterloo", "Tropical Fruit", "sparkling water", "United States", None, "unknown", "Official catalog discovery; exact package and label required", "https://www.drinkwaterloo.com/collections/all", "2026-09-26", "discovery_candidate"),
            ("waterloo-ruby-red-tangerine", "National Beverage Corp.", "Waterloo", "Ruby Red Tangerine", "sparkling water", "United States", None, "unknown", "Official catalog discovery; exact package and label required", "https://www.drinkwaterloo.com/collections/all", "2026-09-26", "discovery_candidate"),
            ("waterloo-grape", "National Beverage Corp.", "Waterloo", "Grape", "sparkling water", "United States", None, "unknown", "Official catalog discovery; exact package and label required", "https://www.drinkwaterloo.com/collections/all", "2026-09-26", "discovery_candidate"),
            ("oatly-full-fat", "Oatly, Inc.", "Oatly Chilled Oatmilk", "Full Fat", "plant-based oat beverage", "United States", "64 oz carton; 1 cup (240 mL) listed serving", "variant", "Manufacturer label page; exact UPC/package match pending", "https://www.oatly.com/en-us/products/chilled-oatmilk/chilled-oatmilk-full-fat-64-oz", "2026-09-26", "needs_package_verification"),
            ("oatly-original", "Oatly, Inc.", "Oatly Chilled Oatmilk", "Original", "plant-based oat beverage", "United States", "64 oz carton", "variant", "Official US nutrition reference; capture current product page label before classification", "https://www.oatly.com/en-us/random-answers/17-facts-about-oatly-and-nutrition", "2026-09-26", "discovery_candidate"),
            ("oatly-low-fat", "Oatly, Inc.", "Oatly Chilled Oatmilk", "Low Fat", "plant-based oat beverage", "United States", "64 oz carton", "variant", "Official US nutrition reference; capture current product page label before classification", "https://www.oatly.com/en-us/random-answers/17-facts-about-oatly-and-nutrition", "2026-09-26", "discovery_candidate"),
            ("oatly-unsweetened", "Oatly, Inc.", "Oatly Chilled Oatmilk", "Unsweetened", "plant-based oat beverage", "United States", "64 oz carton", "variant", "Official US nutrition reference; capture current product page label before classification", "https://www.oatly.com/en-us/random-answers/17-facts-about-oatly-and-nutrition", "2026-09-26", "discovery_candidate"),
            ("olipop-vintage-cola-6g", "OLIPOP", "OLIPOP 6 g fiber", "Vintage Cola", "functional prebiotic soda", "United States", "12 fl oz serving stated for the formula family; exact SKU net format not recorded", "unknown", "Official catalog distinguishes 6 g and 9 g formulas; exact package required", "https://drinkolipop.com/products/", "2026-09-26", "discovery_candidate"),
            ("olipop-classic-root-beer-6g", "OLIPOP", "OLIPOP 6 g fiber", "Classic Root Beer", "functional prebiotic soda", "United States", "12 fl oz serving stated for the formula family; exact SKU net format not recorded", "unknown", "Official catalog distinguishes 6 g and 9 g formulas; exact package required", "https://drinkolipop.com/products/", "2026-09-26", "discovery_candidate"),
            ("olipop-cream-soda-6g", "OLIPOP", "OLIPOP 6 g fiber", "Cream Soda", "functional prebiotic soda", "United States", "12 fl oz serving stated for the formula family; exact SKU net format not recorded", "unknown", "Official catalog distinguishes 6 g and 9 g formulas; exact package required", "https://drinkolipop.com/products/", "2026-09-26", "discovery_candidate"),
        ])
        conn.executemany("INSERT INTO source_records VALUES (?, ?, ?, ?, ?, ?, ?)", [
            ("coca-cola-zero-source", "The Coca-Cola Company", "https://www.coca-cola.com/us/en/brands/coca-cola/products/zero", "United States", "2026-09-24", "manufacturer_page", None),
            ("monster-zero-source", "Monster Energy", "https://www.monsterenergy.com/en-us/energy-drinks/monster-energy/zero-sugar/", "United States", "2026-09-24", "manufacturer_page", None),
        ])
        conn.executemany("INSERT INTO label_versions VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [
            ("coca-cola-zero-2026-09-24", "coca-cola-zero-sugar-12oz-us", "coca-cola-zero-source", "12 fl oz (355 mL)", 1, 0, 0, 0, 0, 40, 34, "Carbonated water, caramel color, phosphoric acid, aspartame, potassium benzoate (to protect taste), natural flavors, potassium citrate, acesulfame potassium, caffeine, stevia extract.", "Phenylketonurics: Contains phenylalanine.", "Zero Sugar", "manufacturer_verified", "2026-09-24", 1),
            ("monster-zero-2026-09-24", "monster-zero-sugar-16oz-us", "monster-zero-source", "16 fl oz (473 mL)", 1, 10, 0, 0, 0, 380, 160, "Carbonated water, citric acid, erythritol, natural flavors, taurine, sodium citrate, Panax ginseng flavor, L-carnitine L-tartrate, caffeine, sucralose, sorbic acid, benzoic acid, fruit juice (color), niacinamide, acesulfame potassium, salt, D-glucuronolactone, guarana extract, inositol, pyridoxine hydrochloride, riboflavin, cyanocobalamin.", None, "Zero Sugar", "needs_package_verification", "2026-09-24", 1),
        ])
        conn.executemany("INSERT INTO ingredients VALUES (?, ?)", [
            ("caffeine", "Caffeine"), ("aspartame", "Aspartame"), ("ace-k", "Acesulfame potassium"), ("sucralose", "Sucralose"), ("erythritol", "Erythritol"), ("taurine", "Taurine"),
        ])
        conn.executemany("INSERT INTO ingredient_profiles VALUES (?, ?, ?, ?, ?, ?)", [
            ("caffeine", "stimulant", "A stimulant that can increase alertness.", "The label amount should be considered alongside all caffeine consumed that day. FDA's 400 mg/day reference is for most healthy adults, not an individual recommendation.", "established_guidance", FDA_CAFFEINE_SOURCE),
            ("aspartame", "high-intensity sweetener", "A low- or no-calorie sweetener used in place of sugar.", "FDA lists an acceptable daily intake of 50 mg/kg/day. Product labels generally do not disclose the amount, so a per-drink comparison is unavailable.", "established_guidance", FDA_SWEETENER_SOURCE),
            ("ace-k", "high-intensity sweetener", "A low- or no-calorie sweetener, also called acesulfame potassium.", "FDA lists an acceptable daily intake of 15 mg/kg/day. Product labels generally do not disclose the amount.", "established_guidance", FDA_SWEETENER_SOURCE),
            ("sucralose", "high-intensity sweetener", "A low- or no-calorie sweetener used in place of sugar.", "FDA lists an acceptable daily intake of 5 mg/kg/day. Product labels generally do not disclose the amount.", "established_guidance", FDA_SWEETENER_SOURCE),
            ("erythritol", "sugar alcohol sweetener", "A sugar alcohol used to provide sweetness with fewer calories than sugar.", "A label amount, when present, is a fact; the ingredient name alone does not establish a personalized health effect.", "limited_or_contextual", None),
            ("taurine", "amino-sulfonic compound", "A compound often added to energy drinks.", "Its presence is not evidence that a drink will improve health or offset sleep loss.", "limited_or_contextual", None),
        ])
        conn.executemany("INSERT INTO label_ingredients VALUES (?, ?, ?, ?, ?, ?, ?)", [
            ("coca-cola-zero-2026-09-24", "aspartame", 1, "High-intensity sweetener", "FDA lists an ADI of 50 mg/kg/day. The label amount is not disclosed, so an intake comparison is unavailable.", "context_matters", FDA_SWEETENER_SOURCE),
            ("coca-cola-zero-2026-09-24", "ace-k", 2, "High-intensity sweetener", "FDA lists an ADI of 15 mg/kg/day. The label amount is not disclosed, so an intake comparison is unavailable.", "context_matters", FDA_SWEETENER_SOURCE),
            ("coca-cola-zero-2026-09-24", "caffeine", 3, "Stimulant", "34 mg per listed serving. FDA's 400 mg/day reference applies to most healthy adults, not every person.", "worth_watching", FDA_CAFFEINE_SOURCE),
            ("monster-zero-2026-09-24", "erythritol", 1, "Sugar alcohol sweetener", "The provisional package transcription lists 2 g per 16 fl oz. A single ingredient does not establish a personalized effect.", "context_matters", None),
            ("monster-zero-2026-09-24", "taurine", 2, "Amino-sulfonic compound", "Common in energy drinks. Do not treat it as a substitute for sleep or nutrition.", "context_matters", None),
            ("monster-zero-2026-09-24", "sucralose", 3, "High-intensity sweetener", "FDA lists an ADI of 5 mg/kg/day. The label amount is not disclosed, so an intake comparison is unavailable.", "context_matters", FDA_SWEETENER_SOURCE),
            ("monster-zero-2026-09-24", "ace-k", 4, "High-intensity sweetener", "FDA lists an ADI of 15 mg/kg/day. The label amount is not disclosed, so an intake comparison is unavailable.", "context_matters", FDA_SWEETENER_SOURCE),
            ("monster-zero-2026-09-24", "caffeine", 5, "Stimulant", "160 mg per listed serving. FDA's 400 mg/day reference applies to most healthy adults, not every person.", "worth_watching", FDA_CAFFEINE_SOURCE),
        ])
    from api.classification import refresh_assessments

    refresh_assessments(DATABASE)
    print(f"Seeded {DATABASE}")


if __name__ == "__main__":
    main()
